services:
  - type: web
    name: tejas-chat-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HF_TOKEN
        sync: false  # This will be set manually in Render dashboard
    healthCheckPath: /health
    autoDeploy: true 